from parking_agent_system.agents.user_agent import ParkingChatAgent
from parking_agent_system.data_layer.vector_manager import ParkingVectorStore
from parking_agent_system.config import settings
from langchain_core.documents import Document

SYSTEM_PROMPT = settings.system_prompt_path.read_text(encoding="utf-8").strip()

class ParkingRAGService:
    def __init__(
        self,
        vector_store: ParkingVectorStore | None = None,
        chat_agent: ParkingChatAgent | None = None,
    ):
        self._vector_store = vector_store if vector_store is not None else ParkingVectorStore()
        self._chat_agent = chat_agent if chat_agent is not None else ParkingChatAgent()


    def _build_context(self, question: str, top_k: int = 3) -> tuple[str, list[Document]]:
        """
        Retrieve public parking knowledge and format it as LLM context.
        
        Args:
            question (str): The user's question.
            top_k (int): Number of top relevant documents to retrieve from the vector store.
        Returns:
            str: Concatenated content of the retrieved documents to be used as context.
            list[Document]: List of retrieved Document objects.
        """
        retrieved_docs = self._vector_store.search(question, top_k=top_k)

        context_parts: list[str] = []

        for document in retrieved_docs:
            title = document.metadata.get("title", "Unknown source")
            document_id = document.metadata.get("document_id", "unknown")

            context_parts.append(
                f"[Source ID: {document_id}]\n"
                f"[Title: {title}]\n"
                f"{document.page_content}"
            )

        context = "\n\n---\n\n".join(context_parts)

        return context, retrieved_docs

    def _construct_messages(self, question: str, context: str) -> list[dict[str, str]]:
        """Build the messages sent to the language model."""
        return [
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": (
                "<retrieved_context>\n"
                f"{context}\n"
                "</retrieved_context>\n\n"
                "<user_question>\n"
                f"{question}\n"
                "</user_question>"
            ),
            },
        ]
        
    def answer_question(
        self,
        question: str,
        top_k: int = 3
    ) -> tuple[str, list[Document]]:
        """
        Answer a user's question using the RAG approach.
        
        Args:
            question (str): The user's question.
            top_k (int): Number of top relevant documents to retrieve from the vector store.
        Returns:
            str: The answer generated by the chat agent.
            list[Document]: List of retrieved Document objects.
        """
        context, retrieved_docs = self._build_context(question, top_k=top_k)
        
        if not retrieved_docs:
            return (
                "I do not have that information in the available parking knowledge base.",
                []
            )

        messages = self._construct_messages(question, context)
        answer = self._chat_agent.generate_response(messages)

        return answer, retrieved_docs
